// src/calendar/Calendar.svelte
<script lang="ts">
  import CalendarControls from './CalendarControls.svelte'
  import CalendarDates from './CalendarDates.svelte'
  import CalendarFooter from './CalendarFooter.svelte'

  let month = $state(new Date())
</script>

<div class="calendar">
  <CalendarControls value={month} onChange={(v) => (month = v)} />
  <CalendarDates {month} />
  <CalendarFooter />
</div>

<style>
  .calendar {
    height: 100vh;
    padding: var(--unit);
  }
</style>

// src/calendar/Calendar.tsx
import React, { useState } from 'react'
import styled from 'styled-components'

import { unit } from './../theme'
import { CalendarControls } from './CalendarControls'
import { CalendarDates } from './CalendarDates'
import { CalendarFooter } from './CalendarFooter'

const CalendarContainer = styled.div`
  height: 100vh;
  padding: ${unit}px;
`

export const Calendar = () => {
  const [month, setMonth] = useState(new Date())

  return (
    <CalendarContainer>
      <CalendarControls value={month} onChange={setMonth} />
      <CalendarDates month={month} />
      <CalendarFooter />
    </CalendarContainer>
  )
}
