// src/calendar/CalendarControls.svelte
<script lang="ts">
  import { addMonths, subMonths, format } from 'date-fns'
  import ChevronLeft from './icons/ChevronLeft.svelte'
  import ChevronRight from './icons/ChevronRight.svelte'

  interface Props {
    value: Date
    onChange: (value: Date) => void
  }

  let { value, onChange }: Props = $props()

  const nextMonth = () => onChange(addMonths(value, 1))
  const previousMonth = () => onChange(subMonths(value, 1))
</script>

<div class="controls">
  <button onclick={previousMonth}>
    <ChevronLeft />
  </button>
  <div class="month">{format(value, 'MMMM - yyyy')}</div>
  <button onclick={nextMonth}>
    <ChevronRight />
  </button>
</div>

<style>
  .controls {
    display: inline-flex;
    flex-flow: row nowrap;
    align-items: center;
    width: 100%;
    height: 60px;
    padding-bottom: var(--unit);
  }

  button {
    cursor: pointer;
    color: color-mix(in srgb, #fff 25%, #474b5c);
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100%;
    width: 60px;
    border: var(--color-border) solid var(--border-width-thin);
    border-radius: var(--border-radius-normal);
    background-color: var(--color-white);
    box-shadow: var(--box-shadow-normal);
    transition: var(--transition-all);
  }

  button:hover,
  button:focus {
    color: var(--color-gray);
    border-color: color-mix(in srgb, #fff 50%, #474b5c);
    box-shadow: var(--box-shadow-large);
  }

  button :global(svg) {
    height: var(--unit);
    width: var(--unit);
  }

  .month {
    flex: 1 1 auto;
    padding: 0 var(--unit);
    text-align: center;
    color: var(--color-gray);
    font-size: var(--font-size-large);
    font-weight: var(--font-weight-bold);
  }

  @media (min-width: 320px) {
    .month {
      font-size: var(--font-size-larger);
    }
  }

  @media (min-width: 768px) {
    .month {
      font-size: var(--font-size-largest);
    }
  }
</style>

// src/calendar/CalendarControls.tsx
import { addMonths, subMonths, format } from 'date-fns'
import { FC } from 'react'
import styled from 'styled-components'

import { unit, mix } from '../theme'
import { ChevronLeft, ChevronRight } from './icons'

export const controlsHeight = unit * 3

const Container = styled.div`
  display: inline-flex;
  flex-flow: row nowrap;
  align-items: center;
  width: 100%;
  height: ${controlsHeight}px;
  padding-bottom: ${unit}px;
`

const Button = styled.button`
  cursor: pointer;
  color: ${$ => mix(0.25, '#fff', $.theme.colors.gray)};
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
  width: ${controlsHeight}px;
  border: ${$ => mix(0.75, '#fff', $.theme.colors.gray)} solid ${$ => $.theme.borderWidths.thin}px;
  border-radius: ${$ => $.theme.borderRadiuses.normal}px;
  background-color: ${$ => $.theme.colors.white};
  box-shadow: ${$ => $.theme.boxShadows.normal};
  transition: ${$ => $.theme.transitions.all};

  &:hover,
  &:focus {
    color: ${$ => $.theme.colors.gray};
    border-color: ${$ => mix(0.5, '#fff', $.theme.colors.gray)};
    box-shadow: ${$ => $.theme.boxShadows.large};
  }

  & > svg {
    height: ${$ => $.theme.unit}px;
    width: ${$ => $.theme.unit}px;

    &:first-child {
      margin-right: ${$ => $.theme.unit / 2}px;
    }

    &:last-child {
      margin-left: ${$ => $.theme.unit / 2}px;
    }
  }
`

const Month = styled.div`
  flex: 1 1 auto;
  padding: 0 ${unit}px;
  text-align: center;
  color: ${$ => $.theme.colors.gray};
  font-size: ${$ => $.theme.fontSizes.large}px;
  font-weight: ${$ => $.theme.fontWeights.bold};

  ${$ => $.theme.media.up('mobile')} {
    font-size: ${$ => $.theme.fontSizes.larger}px;
  }

  ${$ => $.theme.media.up('tablet')} {
    font-size: ${$ => $.theme.fontSizes.largest}px;
  }
`

type CalendarControlsProps = {
  value: Date
  onChange: (value: Date) => void
}

export const CalendarControls: FC<CalendarControlsProps> = ({
  value,
  onChange,
}) => {
  const nextMonth = () => onChange(addMonths(value, 1))
  const previousMonth = () => onChange(subMonths(value, 1))

  return (
    <Container>
      <Button onClick={previousMonth}>
        <ChevronLeft />
      </Button>
      <Month>{format(value, 'MMMM - yyyy')}</Month>
      <Button onClick={nextMonth}>
        <ChevronRight />
      </Button>
    </Container>
  )
}
